### ISSUE TITLE
Unable to set zone

### ISSUE THREAD

**Issue by chunter1** [uwe5/Tasmota-ld2450#1]
Hi,

thank you for sharing your project! :)
I tried to setup a zone and get an unknown command error message:

16:22:26.488 CMD: ld2450_zone0 -1000,1000,0,1000
16:22:26.500 MQT: stat/tasmota_49EA10/RESULT = {"Command":"Unknown"}

Did i miss something?

Thank you!

**Comment by uwe5** [comment]
No, you're right, I changed something without testing. I will upload the new corrected version over the weekend. Sorry

**Comment by uwe5** [comment]
Hello,
I have uploaded a corrected version. I changed the zone parameter, now up to 8 zones can be defined. If there is a target in the zone, this is reported via MQTT.
